services:
  - type: web
    name: task-manager-frontend
    env: node
    buildCommand: cd task-manager-frontend && npm install && npm run build
    startCommand: cd task-manager-frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://your-backend-url.onrender.com 